import http from "node:http";
import {randomUUID,randomBytes,scryptSync,createHmac,timingSafeEqual} from "node:crypto";
import pg from "pg";
import Stripe from "stripe";
const {Pool}=pg;

const port=process.env.PORT||10000;
const AUTH_SECRET=process.env.AUTH_SECRET||"dev-only-change-this-secret";
const stripe=process.env.STRIPE_SECRET_KEY?new Stripe(process.env.STRIPE_SECRET_KEY):null;
const STRIPE_WEBHOOK_SECRET=process.env.STRIPE_WEBHOOK_SECRET||"";
const RIDER_APP_URL=(process.env.RIDER_APP_URL||"https://raider-rides-rider.onrender.com").replace(/\/$/,"");
const DRIVER_APP_URL=(process.env.DRIVER_APP_URL||"https://raider-rides-driver.onrender.com").replace(/\/$/,"");
const ADMIN_APP_URL=(process.env.ADMIN_APP_URL||"https://raider-rides-admin.onrender.com").replace(/\/$/,"");
const DATABASE_URL=process.env.DATABASE_URL||"";
const ADMIN_OWNER_EMAIL=(process.env.ADMIN_OWNER_EMAIL||"").trim().toLowerCase();
const pool=DATABASE_URL?new Pool({connectionString:DATABASE_URL,max:10,idleTimeoutMillis:30000,connectionTimeoutMillis:5000,ssl:/sslmode=require/i.test(DATABASE_URL)?{rejectUnauthorized:false}:undefined}):null;
const memory={users:new Map(),rides:[],drivers:new Map()};
const driverStreams=new Set();
const allowed=(process.env.ALLOWED_ORIGINS||"").split(",").map(x=>x.trim()).filter(Boolean);

const send=(res,status,data)=>{const o=res.reqOrigin;if(!o||!allowed.length||allowed.includes(o))res.setHeader("Access-Control-Allow-Origin",o||"*");res.setHeader("Vary","Origin");res.setHeader("Access-Control-Allow-Headers","Content-Type,Authorization");res.setHeader("Access-Control-Allow-Methods","GET,POST,PATCH,OPTIONS");res.setHeader("Content-Type","application/json");res.writeHead(status);res.end(JSON.stringify(data))};
const body=req=>new Promise((resolve,reject)=>{let s="";req.on("data",c=>s+=c);req.on("end",()=>{try{resolve(s?JSON.parse(s):{})}catch(e){reject(e)}})});
const broadcast=payload=>{const msg="data: "+JSON.stringify(payload)+"\n\n";for(const stream of driverStreams){try{stream.write(msg)}catch{driverStreams.delete(stream)}}};

const hashPassword=password=>{const salt=randomBytes(16).toString("hex");const hash=scryptSync(password,salt,64).toString("hex");return "scrypt$"+salt+"$"+hash};
const verifyPassword=(password,stored)=>{try{const [,salt,hex]=stored.split("$");const actual=scryptSync(password,salt,64);const expected=Buffer.from(hex,"hex");return expected.length===actual.length&&timingSafeEqual(actual,expected)}catch{return false}};
const b64=s=>Buffer.from(s).toString("base64url");
const tokenFor=(user,sessionRole=user.role)=>{const payload=b64(JSON.stringify({sub:user.id,role:sessionRole,accountRole:user.role,exp:Date.now()+1000*60*60*24*30}));const sig=createHmac("sha256",AUTH_SECRET).update(payload).digest("base64url");return payload+"."+sig};
const userFromToken=token=>{try{const [p,s]=String(token||"").split(".");if(!p||!s)return null;const expected=createHmac("sha256",AUTH_SECRET).update(p).digest("base64url");if(!timingSafeEqual(Buffer.from(s),Buffer.from(expected)))return null;const x=JSON.parse(Buffer.from(p,"base64url").toString());return x.exp>Date.now()?x:null}catch{return null}};
const auth=req=>userFromToken((req.headers.authorization||"").replace(/^Bearer\s+/i,""));
const requireAuth=(req,res,roles)=>{const u=auth(req);if(!u)return send(res,401,{message:"Login required"});if(roles&&!roles.includes(u.role))return send(res,403,{message:"Access denied"});return u};

async function initDb(){
 if(!pool)return;
 await pool.query(`CREATE TABLE IF NOT EXISTS users(id uuid PRIMARY KEY,name text NOT NULL,email text UNIQUE NOT NULL,password_hash text NOT NULL,role text NOT NULL CHECK(role IN ('rider','driver','admin')),created_at timestamptz NOT NULL DEFAULT now());
 CREATE TABLE IF NOT EXISTS drivers(user_id uuid PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,online boolean NOT NULL DEFAULT false,rating numeric(3,2) NOT NULL DEFAULT 5,today_earnings numeric(12,2) NOT NULL DEFAULT 0,completed_today integer NOT NULL DEFAULT 0,stripe_account_id text);
 ALTER TABLE drivers ADD COLUMN IF NOT EXISTS stripe_account_id text;
 ALTER TABLE users DROP CONSTRAINT IF EXISTS users_role_check;
 DO $ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='users_role_check') THEN ALTER TABLE users ADD CONSTRAINT users_role_check CHECK(role IN ('rider','driver','admin')); END IF; END $;
 CREATE TABLE IF NOT EXISTS admin_invites(id uuid PRIMARY KEY,token_hash text UNIQUE NOT NULL,email text,created_by uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,used_at timestamptz,created_at timestamptz NOT NULL DEFAULT now());
 CREATE TABLE IF NOT EXISTS rides(id uuid PRIMARY KEY,rider_id uuid NOT NULL REFERENCES users(id),driver_id uuid REFERENCES users(id),status text NOT NULL,pickup text NOT NULL,destination text NOT NULL,ride_type text NOT NULL,passengers integer NOT NULL,fare numeric(12,2) NOT NULL,payment_method text NOT NULL,payment_status text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),accepted_at timestamptz,completed_at timestamptz,payment_confirmed_at timestamptz);
 CREATE INDEX IF NOT EXISTS rides_status_idx ON rides(status);
 CREATE INDEX IF NOT EXISTS rides_rider_idx ON rides(rider_id);
 CREATE INDEX IF NOT EXISTS rides_driver_idx ON rides(driver_id);\n ALTER TABLE rides ADD COLUMN IF NOT EXISTS tip_amount numeric(12,2) NOT NULL DEFAULT 0;\n ALTER TABLE rides ADD COLUMN IF NOT EXISTS tip_paid_at timestamptz;\n ALTER TABLE rides ADD COLUMN IF NOT EXISTS post_tip_amount numeric(12,2) NOT NULL DEFAULT 0;\n ALTER TABLE rides ADD COLUMN IF NOT EXISTS post_tip_paid_at timestamptz;
 ALTER TABLE rides ADD COLUMN IF NOT EXISTS stripe_checkout_session_id text;
 CREATE TABLE IF NOT EXISTS wallets(user_id uuid PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,balance numeric(12,2) NOT NULL DEFAULT 0,currency text NOT NULL DEFAULT 'USD',updated_at timestamptz NOT NULL DEFAULT now());
 CREATE TABLE IF NOT EXISTS wallet_transactions(id uuid PRIMARY KEY,user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,type text NOT NULL,amount numeric(12,2) NOT NULL,ride_id uuid REFERENCES rides(id),description text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
 CREATE TABLE IF NOT EXISTS withdrawal_requests(id uuid PRIMARY KEY,user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,amount numeric(12,2) NOT NULL,payout_account text NOT NULL,status text NOT NULL DEFAULT 'pending',created_at timestamptz NOT NULL DEFAULT now());`);
}
const q=async(sql,params=[])=>pool.query(sql,params);
const mapRide=r=>({id:r.id,riderId:r.rider_id,driverId:r.driver_id,status:r.status,pickup:r.pickup,destination:r.destination,rideType:r.ride_type,passengers:r.passengers,fare:Number(r.fare),paymentMethod:r.payment_method,paymentStatus:r.payment_status,createdAt:r.created_at,acceptedAt:r.accepted_at,completedAt:r.completed_at,paymentConfirmedAt:r.payment_confirmed_at,stripeCheckoutSessionId:r.stripe_checkout_session_id||null,tipAmount:Number(r.tip_amount||0),tipPaidAt:r.tip_paid_at||null,postTipAmount:Number(r.post_tip_amount||0),postTipPaidAt:r.post_tip_paid_at||null});
const fare=b=>Number((12+Math.max(0,String(b.pickup||"").length+String(b.destination||"").length)*.18+(b.rideType==="xl"?7:b.rideType==="premium"?12:0)).toFixed(2));

async function createUser({name,email,password,role}){
 const id=randomUUID(),passwordHash=hashPassword(password);
 if(pool){const r=await q("INSERT INTO users(id,name,email,password_hash,role) VALUES($1,$2,$3,$4,$5) RETURNING id,name,email,role",[id,name,email.toLowerCase(),passwordHash,role]);const u=r.rows[0];if(role==="driver"){await q("INSERT INTO drivers(user_id) VALUES($1)",[id]);await q("INSERT INTO wallets(user_id) VALUES($1)",[id])}return u}
 const u={id,name,email:email.toLowerCase(),passwordHash,role};memory.users.set(u.email,u);if(role==="driver"){memory.drivers.set(id,{userId:id,online:false,rating:5,todayEarnings:0,completedToday:0});memory.wallets=memory.wallets||new Map();memory.wallets.set(id,{balance:0,currency:"USD"})}return u;
}
async function findUser(email){if(pool){const r=await q("SELECT id,name,email,password_hash,role FROM users WHERE email=$1",[email.toLowerCase()]);return r.rows[0]||null}return memory.users.get(email.toLowerCase())||null}
async function profile(userId){if(pool){const r=await q("SELECT u.id,u.name,u.email,u.role,d.online,d.rating,d.today_earnings,d.completed_today FROM users u LEFT JOIN drivers d ON d.user_id=u.id WHERE u.id=$1",[userId]);return r.rows[0]||null}const u=[...memory.users.values()].find(x=>x.id===userId);if(!u)return null;return {...u,...(memory.drivers.get(userId)||{})}}
async function getRidesFor(userId,role){if(pool){const r=role==="rider"?await q("SELECT * FROM rides WHERE rider_id=$1 ORDER BY created_at DESC",[userId]):await q("SELECT * FROM rides ORDER BY created_at DESC",[]);return r.rows.map(mapRide)}return role==="rider"?memory.rides.filter(r=>r.riderId===userId):memory.rides.slice()}
async function saveRide(r){if(pool){const x=await q("INSERT INTO rides(id,rider_id,driver_id,status,pickup,destination,ride_type,passengers,fare,payment_method,payment_status,created_at,tip_amount) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING *",[r.id,r.riderId,r.driverId,r.status,r.pickup,r.destination,r.rideType,r.passengers,r.fare,r.paymentMethod,r.paymentStatus,r.createdAt,Number(r.tipAmount||0)]);return mapRide(x.rows[0])}r.tipAmount=Number(r.tipAmount||0);r.tipPaidAt=null;r.postTipAmount=0;r.postTipPaidAt=null;memory.rides.unshift(r);return r}
async function getRide(id){if(pool){const r=await q("SELECT * FROM rides WHERE id=$1",[id]);return r.rows[0]?mapRide(r.rows[0]):null}return memory.rides.find(r=>r.id===id)||null}
async function updateRide(id,changes){if(pool){const sets=[],vals=[];for(const [k,v] of Object.entries(changes)){const col={driverId:"driver_id",status:"status",acceptedAt:"accepted_at",completedAt:"completed_at",paymentStatus:"payment_status",paymentConfirmedAt:"payment_confirmed_at",stripeCheckoutSessionId:"stripe_checkout_session_id"}[k];if(!col)continue;vals.push(v);sets.push(col+"=$"+vals.length)}if(!sets.length)return getRide(id);vals.push(id);const r=await q("UPDATE rides SET "+sets.join(",")+" WHERE id=$"+vals.length+" RETURNING *",vals);return r.rows[0]?mapRide(r.rows[0]):null}const r=memory.rides.find(x=>x.id===id);if(!r)return null;Object.assign(r,changes);return r}
async function driverStats(userId){if(pool){const r=await q("SELECT online,rating,today_earnings,completed_today FROM drivers WHERE user_id=$1",[userId]);const d=r.rows[0];return d?{online:d.online,rating:Number(d.rating),todayEarnings:Number(d.today_earnings),completedToday:d.completed_today}:null}return memory.drivers.get(userId)||null}
async function setDriverStatus(userId,online){if(pool){const r=await q("UPDATE drivers SET online=$2 WHERE user_id=$1 RETURNING online",[userId,online]);return !!r.rows[0]?.online}const d=memory.drivers.get(userId);if(!d)return false;d.online=online;return d.online}
async function walletInfo(userId){if(pool){const r=await q("SELECT balance,currency FROM wallets WHERE user_id=$1",[userId]);return r.rows[0]?{balance:Number(r.rows[0].balance),currency:r.rows[0].currency}:null}memory.wallets=memory.wallets||new Map();const w=memory.wallets.get(userId)||{balance:0,currency:"USD"};memory.wallets.set(userId,w);return w}
async function creditWallet(userId,amount,rideId,type="ride_earnings",description="80% driver share from completed ride"){if(pool){await q("UPDATE wallets SET balance=balance+$2,updated_at=now() WHERE user_id=$1",[userId,amount]);await q("INSERT INTO wallet_transactions(id,user_id,type,amount,ride_id,description) VALUES($1,$2,$3,$4,$5,$6)",[randomUUID(),userId,type,amount,rideId,description]);return}const w=await walletInfo(userId);w.balance+=amount}
async function creditTipOnce(rideId){if(pool){const r=await q("UPDATE rides SET tip_paid_at=now() WHERE id=$1 AND tip_amount>0 AND tip_paid_at IS NULL AND driver_id IS NOT NULL RETURNING driver_id,tip_amount",[rideId]);if(r.rows[0]){await creditWallet(r.rows[0].driver_id,Number(r.rows[0].tip_amount),rideId,"driver_tip","100% driver tip");return Number(r.rows[0].tip_amount)}return 0}const r=memory.rides.find(x=>x.id===rideId);if(!r||!r.driverId||!r.tipAmount||r.tipPaidAt)return 0;r.tipPaidAt=new Date().toISOString();const w=await walletInfo(r.driverId);w.balance+=Number(r.tipAmount);return Number(r.tipAmount)}
async function creditPostTipOnce(rideId){if(pool){const r=await q("UPDATE rides SET post_tip_paid_at=now() WHERE id=$1 AND post_tip_amount>0 AND post_tip_paid_at IS NULL AND driver_id IS NOT NULL RETURNING driver_id,post_tip_amount",[rideId]);if(r.rows[0]){await creditWallet(r.rows[0].driver_id,Number(r.rows[0].post_tip_amount),rideId,"driver_tip","100% post-payment driver tip");return Number(r.rows[0].post_tip_amount)}return 0}const r=memory.rides.find(x=>x.id===rideId);if(!r||!r.driverId||!r.postTipAmount||r.postTipPaidAt)return 0;r.postTipPaidAt=new Date().toISOString();const w=await walletInfo(r.driverId);w.balance+=Number(r.postTipAmount);return Number(r.postTipAmount)}
async function completeDriver(userId,fareValue,rideId){if(pool){await q("UPDATE drivers SET completed_today=completed_today+1,today_earnings=today_earnings+$2 WHERE user_id=$1",[userId,fareValue]);return}const d=memory.drivers.get(userId);d.completedToday++;d.todayEarnings+=fareValue}

const app=async(req,res)=>{res.reqOrigin=req.headers.origin;if(req.method==="OPTIONS"){send(res,204,{});return}const method=req.method,path=req.url.split("?")[0].replace(/\/$/,"");try{
if(method==="POST"&&path==="/api/stripe/webhook"){if(!stripe)return send(res,503,{message:"Stripe is not configured"});const sig=req.headers["stripe-signature"];let raw="";for await(const chunk of req)raw+=chunk;let event;try{event=STRIPE_WEBHOOK_SECRET?stripe.webhooks.constructEvent(raw,sig,STRIPE_WEBHOOK_SECRET):JSON.parse(raw)}catch(e){return send(res,400,{message:"Invalid Stripe webhook"})}if(event.type==="checkout.session.completed"){const session=event.data.object;const rideId=session.metadata?.rideId;const kind=session.metadata?.kind||"ride_payment";if(rideId&&kind==="post_tip"){await creditPostTipOnce(rideId)}else if(rideId){await updateRide(rideId,{paymentStatus:"paid",stripeCheckoutSessionId:session.id});await creditTipOnce(rideId)}}return send(res,200,{received:true})}
if(method==="GET"&&path==="/api/config/maps"){return send(res,200,{apiKey:process.env.GOOGLE_MAPS_API_KEY||""})}
if(method==="GET"&&path==="/api/health")return send(res,200,{ok:true,service:"raider-rides-api",database:!!pool});
if(method==="POST"&&path==="/api/auth/register"){const b=await body(req);const name=String(b.name||"").trim(),email=String(b.email||"").trim().toLowerCase(),password=String(b.password||""),role=b.role==="driver"?"driver":b.role==="admin"?"admin":"rider";if(name.length<2||!email.includes("@")||password.length<8)return send(res,400,{message:"Name, valid email, and password of at least 8 characters are required"});if(await findUser(email))return send(res,409,{message:"An account with that email already exists"});if(role==="admin"){let authorized=email===ADMIN_OWNER_EMAIL&&!!ADMIN_OWNER_EMAIL;const inviteToken=String(b.inviteToken||"");if(!authorized&&inviteToken){const h=createHmac("sha256",AUTH_SECRET).update(inviteToken).digest("hex");if(pool){const iv=await q("SELECT id FROM admin_invites WHERE token_hash=$1 AND used_at IS NULL AND (email IS NULL OR email=$2)",[h,email]);authorized=!!iv.rows[0]}else{memory.adminInvites=memory.adminInvites||new Map();authorized=memory.adminInvites.has(h)}}if(!authorized)return send(res,403,{message:"Admin access requires the owner email or a team invitation"});const u=await createUser({name,email,password,role});if(b.inviteToken&&pool){const h=createHmac("sha256",AUTH_SECRET).update(String(b.inviteToken)).digest("hex");await q("UPDATE admin_invites SET used_at=now() WHERE token_hash=$1",[h])}return send(res,201,{token:tokenFor(u,"admin"),user:{id:u.id,name:u.name,email:u.email,role:"admin"}})}const u=await createUser({name,email,password,role});return send(res,201,{token:tokenFor(u,role),user:{id:u.id,name:u.name,email:u.email,role}})}
if(method==="POST"&&path==="/api/auth/login"){const b=await body(req),email=String(b.email||"").trim().toLowerCase(),requestedRole=["rider","driver","admin"].includes(b.role)?b.role:"rider",u=await findUser(email);if(!u||!verifyPassword(String(b.password||""),u.password_hash||u.passwordHash))return send(res,401,{message:"Invalid email or password"});let allowedRole=requestedRole==="rider"?(u.role==="rider"||u.role==="driver"||u.role==="admin"):(u.role===requestedRole||u.role==="admin"&&email===ADMIN_OWNER_EMAIL);if(!allowedRole)return send(res,403,{message:"This account is not authorized for "+requestedRole+" access."});if(requestedRole==="admin"&&email===ADMIN_OWNER_EMAIL&&ADMIN_OWNER_EMAIL&&u.role!=="admin"){u.role="admin";if(pool)await q("UPDATE users SET role=$2 WHERE id=$1",[u.id,"admin"]);else memory.users.set(u.email,u)}if(requestedRole==="driver"&&email===ADMIN_OWNER_EMAIL&&ADMIN_OWNER_EMAIL&&u.role==="admin"){if(pool){await q("INSERT INTO drivers(user_id) VALUES($1) ON CONFLICT(user_id) DO NOTHING",[u.id]);await q("INSERT INTO wallets(user_id) VALUES($1) ON CONFLICT(user_id) DO NOTHING",[u.id])}else{memory.drivers=memory.drivers||new Map();memory.drivers.set(u.id,memory.drivers.get(u.id)||{userId:u.id,online:false,rating:5,todayEarnings:0,completedToday:0});memory.wallets=memory.wallets||new Map();memory.wallets.set(u.id,memory.wallets.get(u.id)||{balance:0,currency:"USD"})}}return send(res,200,{token:tokenFor(u,requestedRole),user:{id:u.id,name:u.name,email:u.email,role:requestedRole,accountRole:u.role}})}
if(method==="GET"&&path==="/api/auth/me"){const u=requireAuth(req,res);if(!u)return;const p=await profile(u.sub);return send(res,200,{user:p?{id:p.id,name:p.name,email:p.email,role:p.role}:null})}
if(method==="GET"&&path==="/api/rider/profile"){const u=requireAuth(req,res,["rider"]);if(!u)return;const p=await profile(u.sub);return send(res,200,{id:p.id,name:p.name,email:p.email,role:p.role})}
if(method==="GET"&&path==="/api/rider/rides"){const u=requireAuth(req,res,["rider"]);if(!u)return;return send(res,200,{rides:await getRidesFor(u.sub,"rider")})}
if(method==="POST"&&path==="/api/rides/estimate"){const b=await body(req);const f=fare(b);return send(res,200,{fare:f,estimatedFare:f,durationMinutes:15})}
if(method==="POST"&&path==="/api/rides"){const u=requireAuth(req,res,["rider"]);if(!u)return;const b=await body(req);if(!b.pickup||!b.destination)return send(res,400,{message:"Pickup and destination are required"});const r=await saveRide({id:randomUUID(),riderId:u.sub,driverId:null,status:"requested",pickup:b.pickup,destination:b.destination,rideType:b.rideType||"standard",passengers:Number(b.passengers)||1,fare:fare(b),paymentMethod:b.paymentMethod==="venmo"?"venmo":"cash_app",paymentStatus:"unpaid",createdAt:new Date().toISOString()});broadcast({type:"ride.created",ride:r});return send(res,201,r)}
if(method==="POST"&&path.match(/^\/api\/rides\/[^/]+\/payment-session$/)){const u=requireAuth(req,res,["rider"]);if(!u)return;if(!stripe)return send(res,503,{message:"Card payments are not configured yet."});const id=path.split("/")[3],r=await getRide(id);if(!r||r.riderId!==u.sub)return send(res,404,{message:"Ride not found"});if(!r.driverId||r.status!=="accepted")return send(res,409,{message:"A driver must accept the ride before card payment is available"});const driverAccount=await getDriverStripeAccount(r.driverId);if(!driverAccount)return send(res,409,{message:"This driver has not completed Stripe payout onboarding"});const tipAmount=Math.max(0,Number(r.tipAmount||0)),amount=Math.round((Number(r.fare)+tipAmount)*100),platformFee=Math.round(Number(r.fare)*100*0.20);const session=await stripe.checkout.sessions.create({mode:"payment",customer_email:(await profile(u.sub))?.email,line_items:[{price_data:{currency:"usd",product_data:{name:"Raider Rides trip"},unit_amount:Math.round(Number(r.fare)*100)},quantity:1},{price_data:{currency:"usd",product_data:{name:"Driver tip (100% to driver)"},unit_amount:Math.round(tipAmount*100)},quantity:1}],payment_intent_data:{application_fee_amount:platformFee,transfer_data:{destination:driverAccount},metadata:{rideId:r.id,kind:"ride_payment"}},metadata:{rideId:r.id,kind:"ride_payment",tipAmount:String(tipAmount)},client_reference_id:r.id,success_url:RIDER_APP_URL+"/rider?payment=success&ride="+encodeURIComponent(r.id),cancel_url:RIDER_APP_URL+"/rider?payment=cancelled&ride="+encodeURIComponent(r.id)});await updateRide(r.id,{paymentStatus:"checkout_created",stripeCheckoutSessionId:session.id});return send(res,200,{url:session.url,sessionId:session.id,platformSharePercent:20,driverSharePercent:80})}
if(method==="POST"&&path.match(/^\/api\/rides\/[^/]+\/tip$/)){const u=requireAuth(req,res,["rider"]);if(!u)return;const id=path.split("/")[3],r=await getRide(id),b=await body(req),amount=Number(b.amount);if(!r||r.riderId!==u.sub)return send(res,404,{message:"Ride not found"});if(r.paymentStatus==="paid"||r.paymentStatus==="reported_paid")return send(res,409,{message:"Ride payment is already completed; use the post-payment tip option."});if(!Number.isFinite(amount)||amount<0||amount>1000)return send(res,400,{message:"Tip must be between $0 and $1,000"});const x=await updateRide(id,{tipAmount:Number(amount.toFixed(2))});return send(res,200,x)}
if(method==="POST"&&path.match(/^\/api\/rides\/[^/]+\/payment-confirm$/)){const u=requireAuth(req,res,["rider"]);if(!u)return;const id=path.split("/")[3],r=await getRide(id);if(!r||r.riderId!==u.sub)return send(res,404,{message:"Ride not found"});const x=await updateRide(id,{paymentStatus:"reported_paid",paymentConfirmedAt:new Date().toISOString()});await creditTipOnce(id);return send(res,200,x)}
if(method==="POST"&&path.match(/^\/api\/rides\/[^/]+\/post-tip-session$/)){const u=requireAuth(req,res,["rider"]);if(!u)return;if(!stripe)return send(res,503,{message:"Stripe card payments are not configured yet."});const id=path.split("/")[3],r=await getRide(id),b=await body(req),amount=Number(b.amount);if(!r||r.riderId!==u.sub)return send(res,404,{message:"Ride not found"});if(r.paymentStatus!=="paid"&&r.paymentStatus!=="reported_paid")return send(res,409,{message:"Pay for the ride before adding a post-payment tip"});if(!r.driverId)return send(res,409,{message:"A driver must accept the ride before a tip can be sent"});if(!Number.isFinite(amount)||amount<=0||amount>1000)return send(res,400,{message:"Tip must be between $0.01 and $1,000"});await updateRide(id,{postTipAmount:Number(amount.toFixed(2))});const driverAccount=await getDriverStripeAccount(r.driverId);if(!driverAccount)return send(res,409,{message:"This driver has not completed Stripe payout onboarding"});const cents=Math.round(amount*100);const session=await stripe.checkout.sessions.create({mode:"payment",customer_email:(await profile(u.sub))?.email,line_items:[{price_data:{currency:"usd",product_data:{name:"Raider Rides driver tip (100%)"},unit_amount:cents},quantity:1}],payment_intent_data:{transfer_data:{destination:driverAccount},metadata:{rideId:id,kind:"post_tip"}},metadata:{rideId:id,kind:"post_tip"},client_reference_id:id,success_url:RIDER_APP_URL+"/rider?post_tip=success&ride="+encodeURIComponent(id),cancel_url:RIDER_APP_URL+"/rider?post_tip=cancelled&ride="+encodeURIComponent(id)});return send(res,200,{url:session.url})}
if(method==="POST"&&path.match(/^\/api\/rides\/[^/]+\/post-tip-confirm$/)){const u=requireAuth(req,res,["rider"]);if(!u)return;const id=path.split("/")[3],r=await getRide(id),b=await body(req),amount=Number(b.amount);if(!r||r.riderId!==u.sub)return send(res,404,{message:"Ride not found"});if(r.paymentStatus!=="paid"&&r.paymentStatus!=="reported_paid")return send(res,409,{message:"Pay for the ride first"});if(!Number.isFinite(amount)||amount<=0||amount>1000)return send(res,400,{message:"Tip must be between $0.01 and $1,000"});await updateRide(id,{postTipAmount:Number(amount.toFixed(2))});const credited=await creditPostTipOnce(id);return send(res,200,{status:credited?"tip_added":"tip_pending",amount:Number(amount.toFixed(2))})}
if(method==="GET"&&path==="/api/driver/events"){const query=new URL(req.url,"http://localhost").searchParams;const u=auth(req)||userFromToken(query.get("token"));if(!u)return send(res,401,{message:"Login required"});if(u.role!=="driver")return send(res,403,{message:"Access denied"});res.setHeader("Access-Control-Allow-Origin",res.reqOrigin||"*");res.setHeader("Cache-Control","no-cache");res.setHeader("Connection","keep-alive");res.setHeader("Content-Type","text/event-stream");res.writeHead(200);res.write(": connected\n\n");driverStreams.add(res);const heartbeat=setInterval(()=>{try{res.write(": ping\n\n")}catch{clearInterval(heartbeat);driverStreams.delete(res);try{res.end()}catch{}}},25000);req.on("close",()=>{clearInterval(heartbeat);driverStreams.delete(res)});return}
if(method==="POST"&&path==="/api/driver/stripe/onboarding"){const u=requireAuth(req,res,["driver"]);if(!u)return;if(!stripe)return send(res,503,{message:"Stripe payouts are not configured yet. Add STRIPE_SECRET_KEY to the API service."});let accountId=await getDriverStripeAccount(u.sub);if(!accountId){const p=await profile(u.sub);const account=await stripe.accounts.create({type:"express",country:"US",email:p.email,capabilities:{card_payments:{requested:true},transfers:{requested:true}}});accountId=account.id;await setDriverStripeAccount(u.sub,accountId)}const link=await stripe.accountLinks.create({account:accountId,refresh_url:DRIVER_APP_URL+"/driver?stripe=refresh",return_url:DRIVER_APP_URL+"/driver?stripe=complete",type:"account_onboarding"});return send(res,200,{url:link.url,accountId})}
if(method==="GET"&&path==="/api/driver/stripe/status"){const u=requireAuth(req,res,["driver"]);if(!u)return;if(!stripe)return send(res,200,{configured:false,connected:false});const accountId=await getDriverStripeAccount(u.sub);if(!accountId)return send(res,200,{configured:true,connected:false});const a=await stripe.accounts.retrieve(accountId);return send(res,200,{configured:true,connected:true,accountId,detailsSubmitted:!!a.details_submitted,chargesEnabled:!!a.charges_enabled,payoutsEnabled:!!a.payouts_enabled})}
if(method==="GET"&&path==="/api/driver/wallet"){const u=requireAuth(req,res,["driver"]);if(!u)return;const w=await walletInfo(u.sub);return send(res,200,{balance:Number(w?.balance||0),currency:w?.currency||"USD",driverSharePercent:80})}
if(method==="POST"&&path==="/api/driver/withdraw"){const u=requireAuth(req,res,["driver"]);if(!u)return;const b=await body(req),amount=Number(b.amount),account=String(b.payoutAccount||"").trim();if(!Number.isFinite(amount)||amount<=0)return send(res,400,{message:"Enter a valid withdrawal amount"});if(!account)return send(res,400,{message:"Provide a payout account identifier"});const w=await walletInfo(u.sub);if(amount>w.balance)return send(res,409,{message:"Insufficient wallet balance"});if(pool){await q("UPDATE wallets SET balance=balance-$2,updated_at=now() WHERE user_id=$1",[u.sub,amount]);await q("INSERT INTO withdrawal_requests(id,user_id,amount,payout_account,status) VALUES($1,$2,$3,$4,'pending')",[randomUUID(),u.sub,amount,account]);}else w.balance-=amount;return send(res,202,{status:"pending",amount,balance:Number(w.balance),message:"Withdrawal request created. Connect a payout provider to send funds automatically."})}
if(method==="GET"&&path==="/api/driver/profile"){const u=requireAuth(req,res,["driver"]);if(!u)return;const p=await profile(u.sub),d=await driverStats(u.sub);return send(res,200,{id:p.id,name:p.name,email:p.email,role:p.role,...d})}
if(method==="GET"&&path==="/api/driver/rides"){const u=requireAuth(req,res,["driver"]);if(!u)return;return send(res,200,{rides:await getRidesFor(u.sub,"driver")})}
if(method==="PATCH"&&path==="/api/driver/status"){const u=requireAuth(req,res,["driver"]);if(!u)return;const b=await body(req),online=await setDriverStatus(u.sub,!!b.online);return send(res,200,{online})}
const m=path.match(/^\/api\/driver\/rides\/([^/]+)\/(accept|complete)$/);if(method==="POST"&&m){const u=requireAuth(req,res,["driver"]);if(!u)return;const id=m[1],action=m[2],r=await getRide(id);if(!r)return send(res,404,{message:"Ride not found"});const d=await driverStats(u.sub);if(action==="accept"){if(!d?.online)return send(res,409,{message:"Driver is offline"});const active=(await getRidesFor(u.sub,"driver")).some(x=>x.driverId===u.sub&&x.status==="accepted");if(active)return send(res,409,{message:"Complete your active ride before accepting another"});if(r.status!=="requested"||r.driverId)return send(res,409,{message:"Ride is no longer available"});const x=await updateRide(id,{status:"accepted",driverId:u.sub,acceptedAt:new Date().toISOString()});await creditTipOnce(id);await creditPostTipOnce(id);broadcast({type:"ride.accepted",ride:x});return send(res,200,x)}if(r.status!=="accepted"||r.driverId!==u.sub)return send(res,409,{message:"Only your active ride can be completed"});const x=await updateRide(id,{status:"completed",completedAt:new Date().toISOString()});await completeDriver(u.sub,x.fare);if(x.paymentStatus!=="paid"&&stripe){/* Do not mark unpaid rides as paid; Stripe webhook is authoritative. */}broadcast({type:"ride.completed",ride:x});return send(res,200,x)}
if(method==="POST"&&path==="/api/admin/invites"){const u=requireAuth(req,res,["admin"]);if(!u)return;const b=await body(req),email=String(b.email||"").trim().toLowerCase()||null,token=randomBytes(24).toString("hex"),h=createHmac("sha256",AUTH_SECRET).update(token).digest("hex");if(pool){await q("INSERT INTO admin_invites(id,token_hash,email,created_by) VALUES($1,$2,$3,$4)",[randomUUID(),h,email,u.sub])}else{memory.adminInvites=memory.adminInvites||new Map();memory.adminInvites.set(h,{email,createdBy:u.sub})}return send(res,201,{inviteToken:token,inviteUrl:ADMIN_APP_URL+"?invite="+encodeURIComponent(token),email})}
if(method==="GET"&&path==="/api/admin/stats"){const u=requireAuth(req,res,["admin"]);if(!u)return;const rides=pool?(await q("SELECT * FROM rides",[])).rows.map(mapRide):memory.rides;const online=pool?(await q("SELECT count(*)::int AS n FROM drivers WHERE online=true")).rows[0].n:[...memory.drivers.values()].filter(d=>d.online).length;return send(res,200,{activeRides:rides.filter(r=>!["completed","cancelled"].includes(r.status)).length,driversOnline:Number(online),ridesToday:rides.length,revenueToday:rides.reduce((n,r)=>n+r.fare,0)})}
if(method==="GET"&&path==="/api/admin/rides"){const u=requireAuth(req,res,["admin"]);if(!u)return;const rides=pool?(await q("SELECT * FROM rides ORDER BY created_at DESC",[])).rows.map(mapRide):memory.rides;return send(res,200,{rides})}
if(method==="GET"&&path==="/api/admin/drivers"){const u=requireAuth(req,res,["admin"]);if(!u)return;if(pool){const r=await q("SELECT u.id,u.name,d.online,d.rating,d.today_earnings,d.completed_today FROM users u JOIN drivers d ON d.user_id=u.id ORDER BY u.name");return send(res,200,{drivers:r.rows.map(x=>({id:x.id,name:x.name,online:x.online,rating:Number(x.rating),todayEarnings:Number(x.today_earnings),completedToday:x.completed_today}))})}return send(res,200,{drivers:[...memory.drivers.values()].map(d=>({...d,name:[...memory.users.values()].find(u=>u.id===d.userId)?.name||"Driver"}))})}
return send(res,404,{message:"Not found"})}catch(e){console.error(e);return send(res,500,{message:"Internal server error"})}};

initDb().then(()=>http.createServer(app).listen(port,()=>console.log("Raider Rides API listening on "+port))).catch(e=>{console.error("Database initialization failed",e);if(process.env.REQUIRE_DATABASE==="true")process.exit(1);http.createServer(app).listen(port,()=>console.log("Raider Rides API listening without database"))});