import http from "node:http";
import {randomUUID,randomBytes,scryptSync,createHmac,timingSafeEqual} from "node:crypto";
import pg from "pg";
const {Pool}=pg;

const port=process.env.PORT||10000;
const AUTH_SECRET=process.env.AUTH_SECRET||"dev-only-change-this-secret";
const DATABASE_URL=process.env.DATABASE_URL||"";
const pool=DATABASE_URL?new Pool({connectionString:DATABASE_URL,max:10,idleTimeoutMillis:30000,connectionTimeoutMillis:5000,ssl:/sslmode=require/i.test(DATABASE_URL)?{rejectUnauthorized:false}:undefined}):null;
const memory={users:new Map(),rides:[],drivers:new Map()};
const driverStreams=new Set();
const allowed=(process.env.ALLOWED_ORIGINS||"").split(",").map(x=>x.trim()).filter(Boolean);

const send=(res,status,data)=>{const o=res.reqOrigin;if(!o||!allowed.length||allowed.includes(o))res.setHeader("Access-Control-Allow-Origin",o||"*");res.setHeader("Vary","Origin");res.setHeader("Access-Control-Allow-Headers","Content-Type,Authorization");res.setHeader("Access-Control-Allow-Methods","GET,POST,PATCH,OPTIONS");res.setHeader("Content-Type","application/json");res.writeHead(status);res.end(JSON.stringify(data))};
const body=req=>new Promise((resolve,reject)=>{let s="";req.on("data",c=>s+=c);req.on("end",()=>{try{resolve(s?JSON.parse(s):{})}catch(e){reject(e)}})});
const broadcast=payload=>{const msg="data: "+JSON.stringify(payload)+"\n\n";for(const stream of driverStreams){try{stream.write(msg)}catch{driverStreams.delete(stream)}}};

const hashPassword=password=>{const salt=randomBytes(16).toString("hex");const hash=scryptSync(password,salt,64).toString("hex");return "scrypt$"+salt+"$"+hash};
const verifyPassword=(password,stored)=>{try{const [,salt,hex]=stored.split("$");const actual=scryptSync(password,salt,64);const expected=Buffer.from(hex,"hex");return expected.length===actual.length&&timingSafeEqual(actual,expected)}catch{return false}};
const b64=s=>Buffer.from(s).toString("base64url");
const tokenFor=user=>{const payload=b64(JSON.stringify({sub:user.id,role:user.role,exp:Date.now()+1000*60*60*24*30}));const sig=createHmac("sha256",AUTH_SECRET).update(payload).digest("base64url");return payload+"."+sig};
const userFromToken=token=>{try{const [p,s]=String(token||"").split(".");if(!p||!s)return null;const expected=createHmac("sha256",AUTH_SECRET).update(p).digest("base64url");if(!timingSafeEqual(Buffer.from(s),Buffer.from(expected)))return null;const x=JSON.parse(Buffer.from(p,"base64url").toString());return x.exp>Date.now()?x:null}catch{return null}};
const auth=req=>userFromToken((req.headers.authorization||"").replace(/^Bearer\s+/i,""));
const requireAuth=(req,res,roles)=>{const u=auth(req);if(!u)return send(res,401,{message:"Login required"});if(roles&&!roles.includes(u.role))return send(res,403,{message:"Access denied"});return u};

async function initDb(){
 if(!pool)return;
 await pool.query(`CREATE TABLE IF NOT EXISTS users(id uuid PRIMARY KEY,name text NOT NULL,email text UNIQUE NOT NULL,password_hash text NOT NULL,role text NOT NULL CHECK(role IN ('rider','driver')),created_at timestamptz NOT NULL DEFAULT now());
 CREATE TABLE IF NOT EXISTS drivers(user_id uuid PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,online boolean NOT NULL DEFAULT false,rating numeric(3,2) NOT NULL DEFAULT 5,today_earnings numeric(12,2) NOT NULL DEFAULT 0,completed_today integer NOT NULL DEFAULT 0);
 CREATE TABLE IF NOT EXISTS rides(id uuid PRIMARY KEY,rider_id uuid NOT NULL REFERENCES users(id),driver_id uuid REFERENCES users(id),status text NOT NULL,pickup text NOT NULL,destination text NOT NULL,ride_type text NOT NULL,passengers integer NOT NULL,fare numeric(12,2) NOT NULL,payment_method text NOT NULL,payment_status text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),accepted_at timestamptz,completed_at timestamptz,payment_confirmed_at timestamptz);
 CREATE INDEX IF NOT EXISTS rides_status_idx ON rides(status);
 CREATE INDEX IF NOT EXISTS rides_rider_idx ON rides(rider_id);
 CREATE INDEX IF NOT EXISTS rides_driver_idx ON rides(driver_id);
 CREATE TABLE IF NOT EXISTS wallets(user_id uuid PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,balance numeric(12,2) NOT NULL DEFAULT 0,currency text NOT NULL DEFAULT 'USD',updated_at timestamptz NOT NULL DEFAULT now());
 CREATE TABLE IF NOT EXISTS wallet_transactions(id uuid PRIMARY KEY,user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,type text NOT NULL,amount numeric(12,2) NOT NULL,ride_id uuid REFERENCES rides(id),description text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
 CREATE TABLE IF NOT EXISTS withdrawal_requests(id uuid PRIMARY KEY,user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,amount numeric(12,2) NOT NULL,payout_account text NOT NULL,status text NOT NULL DEFAULT 'pending',created_at timestamptz NOT NULL DEFAULT now());`);
}
const q=async(sql,params=[])=>pool.query(sql,params);
const mapRide=r=>({id:r.id,riderId:r.rider_id,driverId:r.driver_id,status:r.status,pickup:r.pickup,destination:r.destination,rideType:r.ride_type,passengers:r.passengers,fare:Number(r.fare),paymentMethod:r.payment_method,paymentStatus:r.payment_status,createdAt:r.created_at,acceptedAt:r.accepted_at,completedAt:r.completed_at,paymentConfirmedAt:r.payment_confirmed_at});
const fare=b=>Number((12+Math.max(0,String(b.pickup||"").length+String(b.destination||"").length)*.18+(b.rideType==="xl"?7:b.rideType==="premium"?12:0)).toFixed(2));

async function createUser({name,email,password,role}){
 const id=randomUUID(),passwordHash=hashPassword(password);
 if(pool){const r=await q("INSERT INTO users(id,name,email,password_hash,role) VALUES($1,$2,$3,$4,$5) RETURNING id,name,email,role",[id,name,email.toLowerCase(),passwordHash,role]);const u=r.rows[0];if(role==="driver"){await q("INSERT INTO drivers(user_id) VALUES($1)",[id]);await q("INSERT INTO wallets(user_id) VALUES($1)",[id])}return u}
 const u={id,name,email:email.toLowerCase(),passwordHash,role};memory.users.set(u.email,u);if(role==="driver"){memory.drivers.set(id,{userId:id,online:false,rating:5,todayEarnings:0,completedToday:0});memory.wallets=memory.wallets||new Map();memory.wallets.set(id,{balance:0,currency:"USD"})}return u;
}
async function findUser(email){if(pool){const r=await q("SELECT id,name,email,password_hash,role FROM users WHERE email=$1",[email.toLowerCase()]);return r.rows[0]||null}return memory.users.get(email.toLowerCase())||null}
async function profile(userId){if(pool){const r=await q("SELECT u.id,u.name,u.email,u.role,d.online,d.rating,d.today_earnings,d.completed_today FROM users u LEFT JOIN drivers d ON d.user_id=u.id WHERE u.id=$1",[userId]);return r.rows[0]||null}const u=[...memory.users.values()].find(x=>x.id===userId);if(!u)return null;return {...u,...(memory.drivers.get(userId)||{})}}
async function getRidesFor(userId,role){if(pool){const r=role==="rider"?await q("SELECT * FROM rides WHERE rider_id=$1 ORDER BY created_at DESC",[userId]):await q("SELECT * FROM rides ORDER BY created_at DESC",[]);return r.rows.map(mapRide)}return role==="rider"?memory.rides.filter(r=>r.riderId===userId):memory.rides.slice()}
async function saveRide(r){if(pool){const x=await q("INSERT INTO rides(id,rider_id,driver_id,status,pickup,destination,ride_type,passengers,fare,payment_method,payment_status,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING *",[r.id,r.riderId,r.driverId,r.status,r.pickup,r.destination,r.rideType,r.passengers,r.fare,r.paymentMethod,r.paymentStatus,r.createdAt]);return mapRide(x.rows[0])}memory.rides.unshift(r);return r}
async function getRide(id){if(pool){const r=await q("SELECT * FROM rides WHERE id=$1",[id]);return r.rows[0]?mapRide(r.rows[0]):null}return memory.rides.find(r=>r.id===id)||null}
async function updateRide(id,changes){if(pool){const sets=[],vals=[];for(const [k,v] of Object.entries(changes)){const col={driverId:"driver_id",status:"status",acceptedAt:"accepted_at",completedAt:"completed_at",paymentStatus:"payment_status",paymentConfirmedAt:"payment_confirmed_at"}[k];if(!col)continue;vals.push(v);sets.push(col+"=$"+vals.length)}if(!sets.length)return getRide(id);vals.push(id);const r=await q("UPDATE rides SET "+sets.join(",")+" WHERE id=$"+vals.length+" RETURNING *",vals);return r.rows[0]?mapRide(r.rows[0]):null}const r=memory.rides.find(x=>x.id===id);if(!r)return null;Object.assign(r,changes);return r}
async function driverStats(userId){if(pool){const r=await q("SELECT online,rating,today_earnings,completed_today FROM drivers WHERE user_id=$1",[userId]);const d=r.rows[0];return d?{online:d.online,rating:Number(d.rating),todayEarnings:Number(d.today_earnings),completedToday:d.completed_today}:null}return memory.drivers.get(userId)||null}
async function setDriverStatus(userId,online){if(pool){const r=await q("UPDATE drivers SET online=$2 WHERE user_id=$1 RETURNING online",[userId,online]);return !!r.rows[0]?.online}const d=memory.drivers.get(userId);if(!d)return false;d.online=online;return d.online}
async function walletInfo(userId){if(pool){const r=await q("SELECT balance,currency FROM wallets WHERE user_id=$1",[userId]);return r.rows[0]?{balance:Number(r.rows[0].balance),currency:r.rows[0].currency}:null}memory.wallets=memory.wallets||new Map();const w=memory.wallets.get(userId)||{balance:0,currency:"USD"};memory.wallets.set(userId,w);return w}
async function creditWallet(userId,amount,rideId){if(pool){await q("UPDATE wallets SET balance=balance+$2,updated_at=now() WHERE user_id=$1",[userId,amount]);await q("INSERT INTO wallet_transactions(id,user_id,type,amount,ride_id,description) VALUES($1,$2,'ride_earnings',$3,$4,$5)",[randomUUID(),userId,amount,rideId,"80% driver share from completed ride"]);return}const w=await walletInfo(userId);w.balance+=amount}
async function completeDriver(userId,fareValue,rideId){if(pool){await q("UPDATE drivers SET completed_today=completed_today+1,today_earnings=today_earnings+$2 WHERE user_id=$1",[userId,fareValue]);return}const d=memory.drivers.get(userId);d.completedToday++;d.todayEarnings+=fareValue}

const app=async(req,res)=>{res.reqOrigin=req.headers.origin;if(req.method==="OPTIONS"){send(res,204,{});return}const method=req.method,path=req.url.split("?")[0].replace(/\/$/,"");try{
if(method==="GET"&&path==="/api/health")return send(res,200,{ok:true,service:"raider-rides-api",database:!!pool});
if(method==="POST"&&path==="/api/auth/register"){const b=await body(req);const name=String(b.name||"").trim(),email=String(b.email||"").trim().toLowerCase(),password=String(b.password||""),role=b.role==="driver"?"driver":"rider";if(name.length<2||!email.includes("@")||password.length<8)return send(res,400,{message:"Name, valid email, and password of at least 8 characters are required"});if(await findUser(email))return send(res,409,{message:"An account with that email already exists"});const u=await createUser({name,email,password,role});return send(res,201,{token:tokenFor(u),user:{id:u.id,name:u.name,email:u.email,role:u.role}})}
if(method==="POST"&&path==="/api/auth/login"){const b=await body(req),u=await findUser(String(b.email||"").trim().toLowerCase());if(!u||!verifyPassword(String(b.password||""),u.password_hash||u.passwordHash))return send(res,401,{message:"Invalid email or password"});return send(res,200,{token:tokenFor(u),user:{id:u.id,name:u.name,email:u.email,role:u.role}})}
if(method==="GET"&&path==="/api/auth/me"){const u=requireAuth(req,res);if(!u)return;const p=await profile(u.sub);return send(res,200,{user:p?{id:p.id,name:p.name,email:p.email,role:p.role}:null})}
if(method==="GET"&&path==="/api/rider/profile"){const u=requireAuth(req,res,["rider"]);if(!u)return;const p=await profile(u.sub);return send(res,200,{id:p.id,name:p.name,email:p.email,role:p.role})}
if(method==="GET"&&path==="/api/rider/rides"){const u=requireAuth(req,res,["rider"]);if(!u)return;return send(res,200,{rides:await getRidesFor(u.sub,"rider")})}
if(method==="POST"&&path==="/api/rides/estimate"){const b=await body(req);const f=fare(b);return send(res,200,{fare:f,estimatedFare:f,durationMinutes:15})}
if(method==="POST"&&path==="/api/rides"){const u=requireAuth(req,res,["rider"]);if(!u)return;const b=await body(req);if(!b.pickup||!b.destination)return send(res,400,{message:"Pickup and destination are required"});const r=await saveRide({id:randomUUID(),riderId:u.sub,driverId:null,status:"requested",pickup:b.pickup,destination:b.destination,rideType:b.rideType||"standard",passengers:Number(b.passengers)||1,fare:fare(b),paymentMethod:b.paymentMethod==="venmo"?"venmo":"cash_app",paymentStatus:"unpaid",createdAt:new Date().toISOString()});broadcast({type:"ride.created",ride:r});return send(res,201,r)}
if(method==="POST"&&path.match(/^\/api\/rides\/[^/]+\/payment-confirm$/)){const u=requireAuth(req,res,["rider"]);if(!u)return;const id=path.split("/")[3],r=await getRide(id);if(!r||r.riderId!==u.sub)return send(res,404,{message:"Ride not found"});const x=await updateRide(id,{paymentStatus:"reported_paid",paymentConfirmedAt:new Date().toISOString()});return send(res,200,x)}
if(method==="GET"&&path==="/api/driver/events"){const query=new URL(req.url,"http://localhost").searchParams;const u=auth(req)||userFromToken(query.get("token"));if(!u)return send(res,401,{message:"Login required"});if(u.role!=="driver")return send(res,403,{message:"Access denied"});res.setHeader("Access-Control-Allow-Origin",res.reqOrigin||"*");res.setHeader("Cache-Control","no-cache");res.setHeader("Connection","keep-alive");res.setHeader("Content-Type","text/event-stream");res.writeHead(200);res.write(": connected\n\n");driverStreams.add(res);const heartbeat=setInterval(()=>{try{res.write(": ping\n\n")}catch{clearInterval(heartbeat);driverStreams.delete(res);try{res.end()}catch{}}},25000);req.on("close",()=>{clearInterval(heartbeat);driverStreams.delete(res)});return}
if(method==="GET"&&path==="/api/driver/wallet"){const u=requireAuth(req,res,["driver"]);if(!u)return;const w=await walletInfo(u.sub);return send(res,200,{balance:Number(w?.balance||0),currency:w?.currency||"USD",driverSharePercent:80})}
if(method==="POST"&&path==="/api/driver/withdraw"){const u=requireAuth(req,res,["driver"]);if(!u)return;const b=await body(req),amount=Number(b.amount),account=String(b.payoutAccount||"").trim();if(!Number.isFinite(amount)||amount<=0)return send(res,400,{message:"Enter a valid withdrawal amount"});if(!account)return send(res,400,{message:"Provide a payout account identifier"});const w=await walletInfo(u.sub);if(amount>w.balance)return send(res,409,{message:"Insufficient wallet balance"});if(pool){await q("UPDATE wallets SET balance=balance-$2,updated_at=now() WHERE user_id=$1",[u.sub,amount]);await q("INSERT INTO withdrawal_requests(id,user_id,amount,payout_account,status) VALUES($1,$2,$3,$4,'pending')",[randomUUID(),u.sub,amount,account]);}else w.balance-=amount;return send(res,202,{status:"pending",amount,balance:Number(w.balance),message:"Withdrawal request created. Connect a payout provider to send funds automatically."})}
if(method==="GET"&&path==="/api/driver/profile"){const u=requireAuth(req,res,["driver"]);if(!u)return;const p=await profile(u.sub),d=await driverStats(u.sub);return send(res,200,{id:p.id,name:p.name,email:p.email,role:p.role,...d})}
if(method==="GET"&&path==="/api/driver/rides"){const u=requireAuth(req,res,["driver"]);if(!u)return;return send(res,200,{rides:await getRidesFor(u.sub,"driver")})}
if(method==="PATCH"&&path==="/api/driver/status"){const u=requireAuth(req,res,["driver"]);if(!u)return;const b=await body(req),online=await setDriverStatus(u.sub,!!b.online);return send(res,200,{online})}
const m=path.match(/^\/api\/driver\/rides\/([^/]+)\/(accept|complete)$/);if(method==="POST"&&m){const u=requireAuth(req,res,["driver"]);if(!u)return;const id=m[1],action=m[2],r=await getRide(id);if(!r)return send(res,404,{message:"Ride not found"});const d=await driverStats(u.sub);if(action==="accept"){if(!d?.online)return send(res,409,{message:"Driver is offline"});const active=(await getRidesFor(u.sub,"driver")).some(x=>x.driverId===u.sub&&x.status==="accepted");if(active)return send(res,409,{message:"Complete your active ride before accepting another"});if(r.status!=="requested"||r.driverId)return send(res,409,{message:"Ride is no longer available"});const x=await updateRide(id,{status:"accepted",driverId:u.sub,acceptedAt:new Date().toISOString()});broadcast({type:"ride.accepted",ride:x});return send(res,200,x)}if(r.status!=="accepted"||r.driverId!==u.sub)return send(res,409,{message:"Only your active ride can be completed"});const x=await updateRide(id,{status:"completed",completedAt:new Date().toISOString()});await completeDriver(u.sub,x.fare);broadcast({type:"ride.completed",ride:x});return send(res,200,x)}
if(method==="GET"&&path==="/api/admin/stats"){const rides=pool?(await q("SELECT * FROM rides",[])).rows.map(mapRide):memory.rides;const online=pool?(await q("SELECT count(*)::int AS n FROM drivers WHERE online=true")).rows[0].n:[...memory.drivers.values()].filter(d=>d.online).length;return send(res,200,{activeRides:rides.filter(r=>!["completed","cancelled"].includes(r.status)).length,driversOnline:Number(online),ridesToday:rides.length,revenueToday:rides.reduce((n,r)=>n+r.fare,0)})}
if(method==="GET"&&path==="/api/admin/rides"){const rides=pool?(await q("SELECT * FROM rides ORDER BY created_at DESC",[])).rows.map(mapRide):memory.rides;return send(res,200,{rides})}
if(method==="GET"&&path==="/api/admin/drivers"){if(pool){const r=await q("SELECT u.id,u.name,d.online,d.rating,d.today_earnings,d.completed_today FROM users u JOIN drivers d ON d.user_id=u.id ORDER BY u.name");return send(res,200,{drivers:r.rows.map(x=>({id:x.id,name:x.name,online:x.online,rating:Number(x.rating),todayEarnings:Number(x.today_earnings),completedToday:x.completed_today}))})}return send(res,200,{drivers:[...memory.drivers.values()].map(d=>({...d,name:[...memory.users.values()].find(u=>u.id===d.userId)?.name||"Driver"}))})}
return send(res,404,{message:"Not found"})}catch(e){console.error(e);return send(res,500,{message:"Internal server error"})}};

initDb().then(()=>http.createServer(app).listen(port,()=>console.log("Raider Rides API listening on "+port))).catch(e=>{console.error("Database initialization failed",e);if(process.env.REQUIRE_DATABASE==="true")process.exit(1);http.createServer(app).listen(port,()=>console.log("Raider Rides API listening without database"))});