import { api } from "./api.js";
import { shell, card, esc, toast } from "./ui.js";
export function getAuth(){try{return JSON.parse(localStorage.getItem("raiderRidesAuth")||"null")}catch{return null}}
export function setAuth(x){localStorage.setItem("raiderRidesAuth",JSON.stringify(x));localStorage.setItem("raiderRidesToken",x.token)}
export function clearAuth(){localStorage.removeItem("raiderRidesAuth");localStorage.removeItem("raiderRidesToken")}
export async function authScreen(role,render){
 const app=document.querySelector("#app");
 const title=role==="admin"?"Admin login":role==="driver"?"Driver login":"Rider login";
 app.innerHTML=shell(title,role,
   card("Raider Rides account",'<form id="authForm" class="form"><label>Email<input id="authEmail" type="email" autocomplete="email" required></label><label>Password<input id="authPassword" type="password" minlength="8" autocomplete="current-password" required></label><label id="nameWrap" class="hidden">Name<input id="authName" autocomplete="name"></label><div id="driverDocsWrap" class="hidden"><label>License plate<input id="licensePlate" maxlength="20" autocomplete="off" placeholder="ABC-1234"></label><label>Drivers license<input id="licenseDocument" type="file" accept="image/*,.pdf"></label><label>Current insurance<input id="insuranceDocument" type="file" accept="image/*,.pdf"></label><small>Driver documents are private and only available to the driver and authorized Raider Rides administrators. Maximum 10 MB each.</small></div><label id="inviteWrap" class="hidden">Team invite code<input id="inviteToken" autocomplete="off"></label><button id="authSubmit" class="primary" type="submit">Sign in</button></form><button id="toggleAuth" class="secondary" type="button">Create account</button><div id="authMessage" class="gps-status"></div>')
 );
 let register=!!(role==="admin"&&new URLSearchParams(location.search).get("invite"));const inviteFromUrl=role==="admin"?new URLSearchParams(location.search).get("invite"):"";if(inviteFromUrl){const invite=document.querySelector("#inviteToken");if(invite)invite.value=inviteFromUrl;const msg=document.querySelector("#authMessage");msg.innerHTML="<strong>You have been invited to Raider Rides admin access.</strong><br>Use this invitation to create your admin account or sign in to your existing account.";}
 const form=document.querySelector("#authForm"),toggle=document.querySelector("#toggleAuth"),submit=document.querySelector("#authSubmit"),nameWrap=document.querySelector("#nameWrap"),inviteWrap=document.querySelector("#inviteWrap"),driverDocsWrap=document.querySelector("#driverDocsWrap");
 toggle.onclick=()=>{register=!register;nameWrap.classList.toggle("hidden",!register);driverDocsWrap.classList.toggle("hidden",!register||role!=="driver");inviteWrap.classList.toggle("hidden",role!=="admin");submit.textContent=register?"Create account":"Sign in";toggle.textContent=register?"I already have an account":"Create account"};nameWrap.classList.toggle("hidden",!register);driverDocsWrap.classList.toggle("hidden",!register||role!=="driver");inviteWrap.classList.toggle("hidden",!(role==="admin"&&inviteFromUrl));submit.textContent=register?"Create account":"Sign in";toggle.textContent=register?"I already have an account":"Create account";
 form.onsubmit=async e=>{e.preventDefault();const msg=document.querySelector("#authMessage");submit.disabled=true;try{let x;
if(register){
 const readFile=file=>new Promise((resolve,reject)=>{if(!file)return reject(Error("Both driver documents are required."));if(file.size>10*1024*1024)return reject(Error("Each driver document must be 10 MB or smaller."));const fr=new FileReader();fr.onload=()=>resolve(fr.result);fr.onerror=()=>reject(Error("Could not read the selected document."));fr.readAsDataURL(file)});
 const payload={name:document.querySelector("#authName").value,email:document.querySelector("#authEmail").value,password:document.querySelector("#authPassword").value,role,inviteToken:document.querySelector("#inviteToken")?.value.trim()};
 if(role==="driver"){payload.licensePlate=document.querySelector("#licensePlate").value.trim();payload.licenseDocument=await readFile(document.querySelector("#licenseDocument").files[0]);payload.insuranceDocument=await readFile(document.querySelector("#insuranceDocument").files[0])}
 x=await api.auth.register(payload);
}else x=await api.auth.login({email:document.querySelector("#authEmail").value,password:document.querySelector("#authPassword").value,role,inviteToken:document.querySelector("#inviteToken")?.value.trim()});if(x.user.role!==role)throw Error("This account is for "+x.user.role+" access.");setAuth(x);await render()}catch(err){msg.textContent=err.message;toast(err.message)}finally{submit.disabled=false}};
}
