import { api } from "./api.js";
import { shell, card, esc, toast } from "./ui.js";
export function getAuth(){try{const raw=localStorage.getItem("raiderRidesAuth");if(raw)return JSON.parse(raw);const m=document.cookie.match(/(?:^|; )raiderRidesAuth=([^;]+)/);if(m)return JSON.parse(decodeURIComponent(m[1]));return null}catch{return null}}
export function setAuth(x){const raw=JSON.stringify(x);localStorage.setItem("raiderRidesAuth",raw);localStorage.setItem("raiderRidesToken",x.token);document.cookie="raiderRidesAuth="+encodeURIComponent(raw)+"; Max-Age=31536000; Path=/; SameSite=Lax"}
export function clearAuth(){localStorage.removeItem("raiderRidesAuth");localStorage.removeItem("raiderRidesToken");document.cookie="raiderRidesAuth=; Max-Age=0; Path=/; SameSite=Lax"}
async function readDriverFile(file){if(!file)throw Error("Both driver documents are required.");if(file.size>10*1024*1024)throw Error("Each driver document must be 10 MB or smaller.");const raw=await new Promise((resolve,reject)=>{const fr=new FileReader();fr.onload=()=>resolve(fr.result);fr.onerror=()=>reject(Error("Could not read the selected document."));fr.readAsDataURL(file)});if(!file.type.startsWith("image/"))return raw;try{const img=await new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=()=>reject(Error("Could not process the selected image."));i.src=raw});const max=1800,scale=Math.min(1,max/Math.max(img.width,img.height));const canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));canvas.getContext("2d").drawImage(img,0,0,canvas.width,canvas.height);return canvas.toDataURL("image/jpeg",.82)}catch{return raw}}
export async function authScreen(role,render){
 const app=document.querySelector("#app");
 const title=role==="admin"?"Admin login":role==="driver"?"Driver login":"Rider login";
 app.innerHTML=shell(title,role,
   card("Raider Rides account",'<form id="authForm" class="form"><label>Email<input id="authEmail" type="email" autocomplete="email" required></label><label>Password<input id="authPassword" type="password" minlength="8" autocomplete="current-password" required></label><label id="nameWrap" class="hidden">Name<input id="authName" autocomplete="name"></label><div id="driverDocsWrap" class="hidden"><label>License plate<input id="licensePlate" maxlength="20" autocomplete="off" placeholder="ABC-1234"></label><label>Drivers license<input id="licenseDocument" type="file" accept="image/*,.pdf"></label><label>Current insurance<input id="insuranceDocument" type="file" accept="image/*,.pdf"></label><small>Driver documents are private and only available to the driver and authorized Raider Rides administrators. Maximum 10 MB each.</small></div><label id="inviteWrap" class="hidden">Team invite code<input id="inviteToken" autocomplete="off"></label><button id="authSubmit" class="primary" type="submit">Sign in</button></form><button id="toggleAuth" class="secondary" type="button">Create account</button><div id="authMessage" class="gps-status"></div>')
 );
 let register=!!(role==="admin"&&new URLSearchParams(location.search).get("invite"));const inviteFromUrl=role==="admin"?new URLSearchParams(location.search).get("invite"):"";if(inviteFromUrl){const invite=document.querySelector("#inviteToken");if(invite)invite.value=inviteFromUrl;const msg=document.querySelector("#authMessage");msg.innerHTML="<strong>You have been invited to Raider Rides admin access.</strong><br>Use this invitation to create your admin account or sign in to your existing account.";}
 const form=document.querySelector("#authForm"),toggle=document.querySelector("#toggleAuth"),submit=document.querySelector("#authSubmit"),nameWrap=document.querySelector("#nameWrap"),inviteWrap=document.querySelector("#inviteWrap"),driverDocsWrap=document.querySelector("#driverDocsWrap");
 toggle.onclick=()=>{register=!register;nameWrap.classList.toggle("hidden",!register);driverDocsWrap.classList.toggle("hidden",!register||role!=="driver");inviteWrap.classList.toggle("hidden",role!=="admin");submit.textContent=register?"Create account":"Sign in";toggle.textContent=register?"I already have an account":"Create account"};nameWrap.classList.toggle("hidden",!register);driverDocsWrap.classList.toggle("hidden",!register||role!=="driver");inviteWrap.classList.toggle("hidden",!(role==="admin"&&inviteFromUrl));submit.textContent=register?"Create account":"Sign in";toggle.textContent=register?"I already have an account":"Create account";
 form.onsubmit=async e=>{e.preventDefault();const msg=document.querySelector("#authMessage");if(!form.reportValidity())return;submit.disabled=true;submit.textContent=register?"Creating account…":"Signing in…";msg.textContent="";try{let x;if(register){const payload={name:document.querySelector("#authName").value.trim(),email:document.querySelector("#authEmail").value.trim(),password:document.querySelector("#authPassword").value,role,inviteToken:document.querySelector("#inviteToken")?.value.trim()};if(role==="driver"){msg.textContent="Preparing driver documents…";payload.licensePlate=document.querySelector("#licensePlate").value.trim();payload.licenseDocument=await readDriverFile(document.querySelector("#licenseDocument").files[0]);payload.insuranceDocument=await readDriverFile(document.querySelector("#insuranceDocument").files[0]);msg.textContent="Creating driver account…"}x=await api.auth.register(payload)}else{x=await api.auth.login({email:document.querySelector("#authEmail").value.trim(),password:document.querySelector("#authPassword").value,role,inviteToken:document.querySelector("#inviteToken")?.value.trim()})}if(x.user.role!==role)throw Error("This account is for "+x.user.role+" access.");setAuth(x);await render()}catch(err){msg.textContent=err.message;toast(err.message)}finally{submit.disabled=false;submit.textContent=register?"Create account":"Sign in"}};
}
